#spring:
#  application:
#    name: ApiGateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#          url: http://localhost:8761/eureka
#      routes:
#        - id: product-catalog-route
#          uri: lb://PRODUCT-CATALOG-SERVICE
#          predicates:
#            - Path=/product/**
#          filters:
#            - name: RewritePath
#              args:
#                regex: /product/(?<segment>.*)
#                replacement: /${segment}
#        - id: service2-route
#          uri: lb://service2
#          predicates:
#            - Path=/service2/**
#  config:
#    enabled: false
#    import-check:
#      enabled: false
#  activemq:
#    broker-url:
#    close-timeout:
#
#server:
#  port: 8709
#
##eureka:
##  client:
##    service-url:
##      defaultZone: http://localhost:8761/eureka
